server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
        - id: ORDER-PROCESSING-SERVICE
          uri: lb://ORDER-PROCESSING-SERVICE
          predicates:
            - Path=/order/**
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
        - id: PRODUCT-CATALOG-SERVICE
          uri: lb://PRODUCT-CATALOG-SERVICE
          predicates:
            - Path=/product/**

logging:
  level:
    root: DEBUG
    io.micrometer: DEBUG
    brave: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0

