server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: service-routes
          uri: lb://**
          predicates:
            - Path=/**

logging:
  level:
    root: DEBUG
    io.micrometer: DEBUG
    brave: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0

